### ISSUE TITLE
Löschen des Ports in der Settings GUI führt zu invalid cast exception

### ISSUE THREAD

**Issue by FroehDo** [Kreis-Unna/PostNAS_Search#23]
Hallo,

wenn man in der PostNAS-Suche --> Einstellungen GUI den Port für die Verbindung löscht lässt sich das Fenster schließen, das Plugin aber danach nicht mehr laden. Bei jedem Versuch wird eine invalid cast exception (nach integer) geworfen. Eine Neuinstallation des Plugins behebt das Problem nicht. Nur durch Setzen des Ports in der config.json kann das Plugin wieder geladen werden. 

Der Fehler lässt sich beheben indem man in der PostNAS_AccessControl.py:319 vor db.setPort(int(dbPort)) einen Test gegen leer hängt und mit dem default überschreibt:
```
if(dbPort == ""):
    dbPort = "5432"
db.setPort(int(dbPort)) 
```
Grüße aus Freiburg
Dominik Fröhlich

**Comment by FroehDo** [comment]
typo

**Comment by marvinkinberger** [comment]
Fixed
